### ISSUE TITLE
Privacy / GDPR related issues with sending data on behalf of users?

### ISSUE THREAD

**Issue by ctr49** [freifunk-darmstadt/ffda-domain-director#6]
Have you considered that uploading data collected from users (on their behalf) to MLS may be a privacy or even GDPR problem?
Even if the feature is disabled by default, some sort of privacy warning should be displayed when enabling it.

**Comment by blocktrron** [comment]
I have a hard time seeing the "privacy issue". We do not share the connection between location and requesting node with Mozilla as we are acting as a proxy here.

A nodes location can be determined even without a WiFi scan on the node itself as the primary mac is shared and so 2 (or 3/4/6 in worst/best cases) BSSIDs are known to anybody which is enough to determine the location.

>  Even if the feature is disabled by default, some sort of privacy warning should be displayed when enabling it.

While this is no issue for this project, a PR to implement this is welcome in the packages repo.
